// Kyushu Family Trip 2026 — Itinerary Data
// Design: Topographic Field Journal — earthy palette, cartographic aesthetic
// All coordinates verified for accuracy

export type LocationType = "attraction" | "dining" | "transport" | "accommodation";
export type Category = "nature" | "culture" | "food" | "kids" | "transport" | "accommodation" | "hike";

export interface Location {
  id: string;
  name: string;
  type: LocationType;
  category: Category;
  lat: number;
  lng: number;
  description: string;
  kidNotes?: string;
  duration?: string;
  priceRange?: string;
  specialty?: string;
  mealType?: string;
  url?: string;
  tips?: string;
  tags?: string[];
  isOption?: boolean; // multiple options for same slot
  optionGroup?: string; // group name for options
}

export interface DayItinerary {
  id: string;
  date: string;
  dayLabel: string;
  title: string;
  subtitle: string;
  region: string;
  mapCenter: { lat: number; lng: number };
  mapZoom: number;
  heroImage?: string;
  locations: Location[];
  tips: string;
  highlights: string[];
}

const TOPO_BG = "https://d2xsxph8kpxj0f.cloudfront.net/310519663274163203/jRjLAkDKU7GLkhJ5u839XZ/kyushu-topo-bg-iyU5owaEVJCB8g3Ayh6oxC.webp";
const ASO_IMG = "https://d2xsxph8kpxj0f.cloudfront.net/310519663274163203/jRjLAkDKU7GLkhJ5u839XZ/kyushu-aso-volcano-nZ7KtmXk2xLu5qfFfi9qcq.webp";
const KUNISAKI_IMG = "https://d2xsxph8kpxj0f.cloudfront.net/310519663274163203/jRjLAkDKU7GLkhJ5u839XZ/kyushu-kunisaki-bdNqSPmQKQuveA5zW3ftMh.webp";

export const itinerary: DayItinerary[] = [
  // ─── APR 15: ARRIVAL ───────────────────────────────────────────────────────
  {
    id: "apr15",
    date: "Apr 15",
    dayLabel: "Day 1",
    title: "Arrival at Kansai",
    subtitle: "Landing & settling in at Rinku Town",
    region: "Osaka / Rinku Town",
    mapCenter: { lat: 34.409, lng: 135.297 },
    mapZoom: 14,
    heroImage: TOPO_BG,
    tips: "You're staying at OMO Kansai Airport — it's right in the terminal area, so no long transfers after a flight with two little ones. Rinku Pleasure Town Seacle is a 5-minute walk and has indoor play areas perfect for burning off post-flight energy.",
    highlights: ["Indoor play area for toddlers", "Ferris wheel views", "Easy airport access"],
    locations: [
      {
        id: "omo-kansai",
        name: "OMO Kansai Airport",
        type: "accommodation",
        category: "accommodation",
        lat: 34.4338,
        lng: 135.2263,
        description: "Your base for the night — a Hoshino Resorts property connected to Kansai Airport. The OMO brand is designed for urban explorers and offers a relaxed, modern stay with helpful local guides.",
        kidNotes: "Very convenient for families — no long transfers after landing. Kids can unwind quickly.",
        tags: ["Accommodation", "Airport"],
      },
      {
        id: "rinku-park",
        name: "Rinku Park",
        type: "attraction",
        category: "nature",
        lat: 34.4091,
        lng: 135.2977,
        description: "A vast waterside park with sweeping views of Kansai International Airport across the bay. Features Marble Beach (smooth pebbles), a fountain garden, and wide open lawns. Perfect for watching planes take off and land.",
        kidNotes: "Huge open space for toddlers to run freely. Plane spotting is a big hit with young kids. The pebble beach is a fun sensory experience.",
        duration: "1–2 hours",
        url: "https://rinku.osaka-park.or.jp/english",
        tags: ["Park", "Plane Spotting", "Beach"],
      },
      {
        id: "yu-kids",
        name: "Yu Kids Indoor Playland",
        type: "attraction",
        category: "kids",
        lat: 34.4063,
        lng: 135.2959,
        description: "An all-weather indoor playland on the 2nd floor of Rinku Pleasure Town Seacle, featuring 30+ innovative play structures designed for children aged 0–8. LED lights, soft mats, and unique climbing structures make this a toddler paradise.",
        kidNotes: "Ideal for ages 0–8. Guardians enter free. ¥600/hour per child. Perfect if the kids need to burn energy after the flight.",
        duration: "1–2 hours",
        priceRange: "¥600/hour per child",
        url: "https://yukids.net/",
        tags: ["Indoor Play", "Toddler", "All Weather"],
      },
      {
        id: "rinku-ferris",
        name: "Rinku no Hoshi Ferris Wheel",
        type: "attraction",
        category: "kids",
        lat: 34.4088,
        lng: 135.2974,
        description: "An 85-meter Ferris wheel at Rinku Pleasure Town Seacle offering panoramic views of Kansai Airport, the Izumi Mountains, and Osaka Bay. A gentle, memorable first evening activity.",
        kidNotes: "Children under elementary school age must ride with a paying guardian. A magical way to end the first day of the trip.",
        duration: "15–30 minutes",
        url: "https://www.seacle.jp/",
        tags: ["Ferris Wheel", "Views", "Evening"],
      },
      {
        id: "rinku-dinner",
        name: "Rinku Pleasure Town Seacle Food Court",
        type: "dining",
        category: "food",
        lat: 34.4063,
        lng: 135.2959,
        description: "The Seacle complex has multiple family-friendly dining options including Japanese set meals, ramen, and casual Western food. Convenient, affordable, and easy with toddlers.",
        kidNotes: "Multiple options under one roof — easy to find something for picky eaters. High chairs available.",
        mealType: "Dinner",
        priceRange: "¥800–¥1,500 per person",
        tags: ["Dinner", "Family Friendly", "Casual"],
      },
    ],
  },

  // ─── APR 16: KUMAMOTO ──────────────────────────────────────────────────────
  {
    id: "apr16",
    date: "Apr 16",
    dayLabel: "Day 2",
    title: "Kumamoto City",
    subtitle: "Shinkansen south, then drive to Hakushu",
    region: "Kumamoto City → Kikuchi / Hakushu",
    mapCenter: { lat: 32.803, lng: 130.706 },
    mapZoom: 13,
    heroImage: TOPO_BG,
    tips: "Take the Shinkansen from Shin-Osaka to Kumamoto (about 3.5 hours). Pick up your rental car at Kumamoto Station. Allow 2–3 hours to explore the city before the drive north to Hakushu/Kikuchi area (about 45 min). The drive through Kikuchi Gorge is beautiful in spring.",
    highlights: ["Kumamoto Castle", "Kumamon mascot", "Suizenji Garden"],
    locations: [
      {
        id: "kumamoto-castle",
        name: "Kumamoto Castle",
        type: "attraction",
        category: "culture",
        lat: 32.8061,
        lng: 130.706,
        description: "One of Japan's three great castles, known for its dramatic stone walls and imposing black keep. The castle and grounds are stroller-friendly with elevators available. The surrounding park is beautiful in spring with cherry blossoms.",
        kidNotes: "Strollers allowed throughout. Elevators available. The wide castle grounds give kids plenty of space to roam. The castle itself is visually impressive even for young children.",
        duration: "1.5–2 hours",
        priceRange: "¥800 adults, free under 6",
        url: "https://castle.kumamoto-guide.jp/en/info/",
        tags: ["Castle", "History", "Stroller Friendly"],
      },
      {
        id: "kumamon-square",
        name: "Kumamon Square",
        type: "attraction",
        category: "kids",
        lat: 32.8018,
        lng: 130.7125,
        description: "The official home base of Kumamon, Kumamoto's beloved bear mascot. Features live Kumamon performances, AR games, photo spots, and a shop/café. Free admission makes this a must-stop.",
        kidNotes: "Kids absolutely love meeting Kumamon. Free entry. Live performances several times daily — check the schedule. Great for photos.",
        duration: "1–1.5 hours",
        priceRange: "Free",
        url: "https://www.kumamon-sq.jp/en/",
        tags: ["Mascot", "Free", "Kids Favourite"],
      },
      {
        id: "suizenji-garden",
        name: "Suizenji Jojuen Garden",
        type: "attraction",
        category: "nature",
        lat: 32.7911,
        lng: 130.7346,
        description: "A stunning 350-year-old strolling garden featuring a miniature Mt. Fuji mound, serene koi ponds, and traditional landscaping inspired by the 53 stations of the Tokaido road. Especially beautiful in spring.",
        kidNotes: "Mostly flat, wide paths — very stroller-friendly. Kids love watching the koi fish. Free for children under 6.",
        duration: "45 min–1.5 hours",
        priceRange: "¥400 adults, free under 6",
        url: "https://lunitravels.com/suizenji-jojuen-garden/",
        tags: ["Garden", "Koi", "Stroller Friendly"],
      },
      {
        id: "hale-cafe",
        name: "HALE CAFÉ Tsunagu",
        type: "dining",
        category: "food",
        lat: 32.8069,
        lng: 130.712,
        description: "A warm, home-style Japanese restaurant near Kumamoto Castle serving fresh local ingredients. The 'Select Menu' lets you choose from rice, soup, salad, and mains like hand-kneaded Hamburg steak and Chicken Namban.",
        kidNotes: "Has a dedicated kids' play space and shoeless seating — very relaxed for families. Private rooms with sofa seating available (reservation recommended).",
        mealType: "Lunch",
        priceRange: "¥1,000–¥2,000",
        tags: ["Lunch", "Japanese", "Kids Space"],
      },
      {
        id: "kikyoya",
        name: "Kikyoya",
        type: "dining",
        category: "food",
        lat: 32.799,
        lng: 130.7034,
        description: "A well-regarded traditional Japanese restaurant famous for its generous 50-item set lunch. Offers private rooms and a relaxed atmosphere — perfect for families who need space.",
        kidNotes: "Completely private rooms allow children to be themselves without worrying about other diners. Staff can prepare cushions and child-friendly items if informed in advance.",
        mealType: "Lunch",
        priceRange: "¥2,000–¥3,000",
        tags: ["Lunch", "Private Room", "Set Meal"],
      },
    ],
  },

  // ─── APR 17: ASO DAY 1 ─────────────────────────────────────────────────────
  {
    id: "apr17",
    date: "Apr 17",
    dayLabel: "Day 3",
    title: "Into the Caldera",
    subtitle: "Aso's volcanic landscapes & meadows",
    region: "Aso, Kumamoto",
    mapCenter: { lat: 32.93, lng: 131.07 },
    mapZoom: 11,
    heroImage: ASO_IMG,
    tips: "Check the volcanic activity status at Mt. Aso before heading to the crater area — access to Nakadake crater is occasionally restricted. Kusasenri meadow is always accessible and is the highlight for young kids. Dress in layers; the caldera rim can be cool even in April.",
    highlights: ["Kusasenri grassland meadow", "Daikanbo panoramic viewpoint", "Aso Shrine"],
    locations: [
      {
        id: "daikanbo",
        name: "Daikanbo Viewpoint",
        type: "attraction",
        category: "nature",
        lat: 32.9654,
        lng: 131.0845,
        description: "The most dramatic viewpoint on the Aso caldera's northeast rim. From here you can see all five Aso peaks lined up across the vast caldera floor — one of Japan's most spectacular panoramas. The wind rushing up the ridge adds to the drama.",
        kidNotes: "Very easy to access from the parking area — just a short walk to the viewpoint. Can be windy, so dress toddlers warmly. The view is breathtaking and memorable.",
        duration: "20–30 minutes",
        priceRange: "Free",
        tags: ["Viewpoint", "Volcano", "Panorama"],
      },
      {
        id: "kusasenri",
        name: "Kusasenri Meadow",
        type: "attraction",
        category: "hike",
        lat: 32.8847,
        lng: 131.0551,
        description: "A perfectly circular ancient crater about 1km across, now a sweeping grassland with two shallow ponds. Horses graze freely across the meadow. In April the grass is fresh green with wildflowers. One of the most serene landscapes in Japan.",
        kidNotes: "Completely flat — perfect for toddlers to walk and run freely. Seeing the grazing horses up close is magical for young children. Very easy 30-minute loop walk.",
        duration: "45 min–1 hour",
        priceRange: "Free (parking ¥300)",
        tags: ["Meadow", "Easy Walk", "Horses", "Nature"],
      },
      {
        id: "aso-shrine",
        name: "Aso Shrine",
        type: "attraction",
        category: "culture",
        lat: 32.9478,
        lng: 131.116,
        description: "One of Japan's oldest and most important Shinto shrines, dedicated to 12 deities who are believed to be family members. The approach street (Monzenmachi) has charming old shops and cafés. Currently undergoing post-earthquake restoration.",
        kidNotes: "The flat approach street is stroller-friendly. A calm, spiritual atmosphere. The surrounding Monzenmachi has small shops where kids can browse.",
        duration: "1–1.5 hours",
        priceRange: "Free",
        tags: ["Shrine", "Culture", "Stroller Friendly"],
      },
      {
        id: "imakin-shokudo",
        name: "Imakin Shokudo",
        type: "dining",
        category: "food",
        lat: 32.975,
        lng: 131.0393,
        description: "A beloved traditional diner near Aso Station famous for its Akagyu (Aso red beef) rice bowls. The minced beef bowl is excellent value at ¥790. A rustic wooden interior with an authentic local atmosphere.",
        kidNotes: "Arrive early (before 11am) to avoid long queues — very popular. The minced beef bowl is a good affordable option. Staff are friendly and patient.",
        mealType: "Lunch",
        priceRange: "¥790–¥2,100",
        specialty: "Akagyu (Aso Red Beef) rice bowl",
        tags: ["Lunch", "Local Beef", "Iconic"],
      },
      {
        id: "aso-milk-factory",
        name: "Aso Milk Factory",
        type: "dining",
        category: "food",
        lat: 32.9761,
        lng: 131.0511,
        description: "Located at Aso Station, this dairy shop serves fresh Aso milk, cheese, yogurt, ice cream, and baked goods made from the famous Aso plateau dairy. A perfect snack stop with locally-made products.",
        kidNotes: "Kids love the fresh soft-serve ice cream. A great quick stop for dairy snacks. The milk is exceptionally fresh and creamy.",
        mealType: "Snack / Breakfast",
        priceRange: "¥300–¥800",
        specialty: "Fresh Aso milk, soft-serve ice cream",
        tags: ["Snack", "Dairy", "Local"],
      },
    ],
  },

  // ─── APR 18: ASO DAY 2 ─────────────────────────────────────────────────────
  {
    id: "apr18",
    date: "Apr 18",
    dayLabel: "Day 4",
    title: "Aso Farm & Ranch Day",
    subtitle: "Animals, dairy, and open countryside",
    region: "Aso, Kumamoto",
    mapCenter: { lat: 32.87, lng: 131.0 },
    mapZoom: 11,
    heroImage: ASO_IMG,
    tips: "Today is a great day to slow down and let the kids lead. The Aso Milk Ranch is a highlight for young children — feeding goats and sheep is endlessly entertaining. Consider a morning at the ranch and an afternoon at Aso Farm Land if energy allows.",
    highlights: ["Aso Milk Ranch animal feeding", "Aso Farm Land play area", "Countryside drive"],
    locations: [
      {
        id: "aso-milk-ranch",
        name: "Aso Milk Ranch (Raigumo Mothers)",
        type: "attraction",
        category: "kids",
        lat: 32.7982,
        lng: 130.9089,
        description: "A working dairy ranch where children can feed goats, sheep, and ponies at the Animal Petting Plaza. Also offers cow milking experiences, pony rides, animal races, and a cheese factory tour. Set against the stunning Aso mountain backdrop.",
        kidNotes: "Perfect for ages 2–4. Feeding the animals is the highlight — kids can get right up close. Pony rides are available. Bring cash for animal feed (¥100–200).",
        duration: "2–3 hours",
        priceRange: "¥500–¥1,000 entry + activities",
        url: "https://aso-milk.jp/en/",
        tags: ["Animals", "Farm", "Pony Ride", "Toddler"],
      },
      {
        id: "aso-farm-land",
        name: "Aso Genki no Mori (Aso Farm Land)",
        type: "attraction",
        category: "kids",
        lat: 32.8983,
        lng: 131.0068,
        description: "A vast health-themed resort covering 1 million square meters with giant mazes, slides, labyrinths, and a 'Fureai Animal Kingdom' where kids can interact with capybaras, flamingos, and small animals. Also has unique dome-shaped accommodation.",
        kidNotes: "Enormous play area — plan for a half or full day. The giant maze and slides are great for 4-year-olds. The animal interaction area suits the 2-year-old perfectly.",
        duration: "Half-day to full-day",
        priceRange: "¥1,000–¥1,500 entry",
        url: "https://asotravel.com/",
        tags: ["Theme Park", "Animals", "Playground", "Kids"],
      },
      {
        id: "yamasoku-tabiji",
        name: "Yamasoku Tabiji",
        type: "dining",
        category: "food",
        lat: 32.9336,
        lng: 131.0701,
        description: "A charming local restaurant about 1km from Aso Station with traditional mat or table seating. Specialises in home-style rice and noodle dishes and affordable set meals using local ingredients.",
        kidNotes: "Relaxed, unhurried atmosphere. Traditional seating with cushions — kids can sit comfortably. Good value set meals.",
        mealType: "Lunch",
        priceRange: "¥800–¥1,500",
        specialty: "Home-style rice and noodle dishes",
        tags: ["Lunch", "Local", "Affordable"],
      },
      {
        id: "aso-hanabishi",
        name: "Aso Hanabishi",
        type: "dining",
        category: "food",
        lat: 32.9373,
        lng: 131.1071,
        description: "A cosy restaurant with beautiful wooden beam interiors serving Aso black wagyu beef dishes — cutlets, curries, soups, and stews. One of the best places to try high-quality local beef at reasonable prices.",
        kidNotes: "Arrive early to avoid waits. The beef curry is mild enough for older toddlers. Warm, welcoming atmosphere.",
        mealType: "Lunch",
        priceRange: "¥1,500–¥2,500",
        specialty: "Aso black wagyu beef cutlets & curry",
        tags: ["Lunch", "Wagyu Beef", "Cosy"],
      },
    ],
  },

  // ─── APR 19: ASO DAY 3 ─────────────────────────────────────────────────────
  {
    id: "apr19",
    date: "Apr 19",
    dayLabel: "Day 5",
    title: "Southern Aso & Springs",
    subtitle: "Shirakawa spring, Takachiho option, countryside",
    region: "South Aso / Takachiho",
    mapCenter: { lat: 32.78, lng: 131.05 },
    mapZoom: 10,
    heroImage: ASO_IMG,
    tips: "Shirakawa Suigen spring is one of Japan's most beautiful natural springs — arrive early morning for the best light and fewer crowds. Takachiho Gorge is a 1.5-hour drive but absolutely worth it if the kids are up for it. The boat ride through the gorge is unforgettable.",
    highlights: ["Shirakawa Suigen crystal-clear spring", "Takachiho Gorge boat ride (option)", "Minamiaso Railway"],
    locations: [
      {
        id: "shirakawa-suigen",
        name: "Shirakawa Suigen Spring",
        type: "attraction",
        category: "nature",
        lat: 32.8374,
        lng: 131.0817,
        description: "One of Japan's 100 famous waters — a crystal-clear spring where 60 tonnes of pure water emerge per minute from the base of Mt. Aso. The water is so clear you can see every pebble on the bottom. Surrounded by ancient trees and a small shrine.",
        kidNotes: "Easy flat walk around the spring. The crystal-clear water is mesmerising for children. Very photogenic. Arrive early for the best experience.",
        duration: "30–45 minutes",
        priceRange: "Free",
        tags: ["Spring", "Nature", "Crystal Water"],
      },
      {
        id: "takachiho-gorge",
        name: "Takachiho Gorge",
        type: "attraction",
        category: "hike",
        lat: 32.7072,
        lng: 131.3058,
        description: "A dramatic gorge carved by the Gokase River through columnar basalt cliffs, with a beautiful waterfall (Manai Falls) at its heart. Rowboats can be rented to paddle through the gorge — one of Kyushu's most iconic experiences.",
        kidNotes: "The boat ride (¥2,000/30 min, max 3 people) is the highlight — kids love it. The walking path along the gorge is paved and manageable with a carrier for the 2-year-old. About 1.5 hours drive from Aso.",
        duration: "2–3 hours (including drive)",
        priceRange: "¥2,000 for boat rental",
        url: "https://takachiho-kanko.info/en/sightseeing/takachihogorge.php",
        tags: ["Gorge", "Boat Ride", "Waterfall", "Day Trip"],
        isOption: true,
        optionGroup: "apr19-main",
      },
      {
        id: "minamiaso-railway",
        name: "Minamiaso Railway (Torokko Train)",
        type: "attraction",
        category: "kids",
        lat: 32.8208,
        lng: 130.9972,
        description: "A scenic open-air 'torokko' (trolley) train that runs through the southern Aso countryside with stunning views of the caldera and mountains. A delightful slow journey through rural Japan.",
        kidNotes: "Kids love the open-air carriages. The slow pace and mountain views make it a relaxing experience. Check seasonal schedules as the torokko car runs on weekends and holidays.",
        duration: "1–1.5 hours",
        priceRange: "¥1,000–¥1,500",
        tags: ["Train", "Scenic", "Kids Love"],
        isOption: true,
        optionGroup: "apr19-main",
      },
      {
        id: "michinoeki-aso",
        name: "Michinoeki Aso (Road Station)",
        type: "dining",
        category: "food",
        lat: 32.9345,
        lng: 131.0702,
        description: "A well-stocked roadside station near Aso with a food court, local produce market, and multiple affordable dining options. Great for a quick, satisfying meal using local Aso ingredients.",
        kidNotes: "Easy, no-fuss dining. Multiple options so everyone can find something. Local dairy products and snacks available to take away.",
        mealType: "Breakfast / Lunch",
        priceRange: "¥600–¥1,200",
        specialty: "Local Aso produce, dairy, noodles",
        tags: ["Road Station", "Casual", "Local Produce"],
      },
    ],
  },

  // ─── APR 20: ASO DAY 4 ─────────────────────────────────────────────────────
  {
    id: "apr20",
    date: "Apr 20",
    dayLabel: "Day 6",
    title: "Aso Rest & Explore",
    subtitle: "Onsen, easy walks, and local life",
    region: "Aso / Uchinomaki",
    mapCenter: { lat: 32.96, lng: 131.05 },
    mapZoom: 12,
    heroImage: ASO_IMG,
    tips: "A good day to slow down before the drive to Kunisaki tomorrow. Uchinomaki Onsen is a charming hot spring town with foot baths (ashiyu) that are perfect for toddlers. The Aso Cuddly Dominion is a great option if the kids want more animal time.",
    highlights: ["Uchinomaki Onsen foot bath", "Aso Cuddly Dominion bear park", "Relaxed countryside morning"],
    locations: [
      {
        id: "aso-cuddly-dominion",
        name: "Aso Cuddly Dominion",
        type: "attraction",
        category: "kids",
        lat: 32.9475,
        lng: 131.1358,
        description: "An animal theme park where visitors can interact closely with bears, alpacas, ostriches, guinea pigs, rabbits, and penguins. Highlights include holding a baby black bear, animal shows at 'Cuddly Hall', and feeding penguins.",
        kidNotes: "Holding a baby bear is a once-in-a-lifetime experience for children. The animal shows are entertaining for all ages. Very manageable size — not overwhelming.",
        duration: "2–3 hours",
        priceRange: "¥1,500–¥2,000 adults, ¥800–¥1,000 children",
        url: "https://www.cuddly.co.jp/eng.html",
        tags: ["Animals", "Bears", "Shows", "Kids"],
      },
      {
        id: "uchinomaki-onsen",
        name: "Uchinomaki Onsen Town",
        type: "attraction",
        category: "nature",
        lat: 32.9612,
        lng: 131.0742,
        description: "A charming traditional hot spring town with free public foot baths (ashiyu) along the main street. The town has a lovely old-Japan atmosphere with ryokan, small shops, and a relaxed pace.",
        kidNotes: "Free foot baths are perfect for toddlers — warm, safe, and fun. A great way to introduce young children to onsen culture without the full bath commitment.",
        duration: "1 hour",
        priceRange: "Free (foot baths)",
        tags: ["Onsen", "Foot Bath", "Traditional Town"],
      },
      {
        id: "aso-nature-walk",
        name: "Aso Caldera Rim Walk",
        type: "attraction",
        category: "hike",
        lat: 32.8847,
        lng: 131.0551,
        description: "A gentle walk along the caldera rim near Kusasenri with panoramic views of the volcanic landscape. The path is mostly flat and well-maintained, offering stunning views without any strenuous climbing.",
        kidNotes: "Very manageable for young children — mostly flat with wide paths. The volcanic scenery is dramatic and educational. Bring a carrier for the 2-year-old on uneven sections.",
        duration: "1–2 hours",
        priceRange: "Free",
        tags: ["Easy Walk", "Volcano Views", "Nature"],
      },
      {
        id: "aso-milk-factory-2",
        name: "Aso Milk Factory (Breakfast)",
        type: "dining",
        category: "food",
        lat: 32.9761,
        lng: 131.0511,
        description: "Start the day with fresh Aso dairy products — milk, yogurt, cheese, and baked goods at this charming station café. The morning light at Aso Station is beautiful.",
        kidNotes: "Fresh milk and yogurt are perfect for toddlers. Light, nutritious breakfast option.",
        mealType: "Breakfast",
        priceRange: "¥300–¥800",
        specialty: "Fresh dairy, yogurt, baked goods",
        tags: ["Breakfast", "Dairy", "Light"],
      },
    ],
  },

  // ─── APR 21: KUNISAKI DAY 1 ────────────────────────────────────────────────
  {
    id: "apr21",
    date: "Apr 21",
    dayLabel: "Day 7",
    title: "Kunisaki Peninsula",
    subtitle: "Ancient temples, rock carvings & farmstay arrival",
    region: "Kunisaki, Oita",
    mapCenter: { lat: 33.52, lng: 131.47 },
    mapZoom: 11,
    heroImage: KUNISAKI_IMG,
    tips: "The drive from Aso to Kunisaki takes about 2.5 hours via the expressway. Kunisaki is one of Japan's most spiritually rich and least-visited peninsulas — a hidden gem. The Kumano Magaibutsu rock carvings require a short but steep climb; use a carrier for the 2-year-old.",
    highlights: ["Kumano Magaibutsu rock carvings", "Fuki-ji ancient temple", "Farmstay arrival"],
    locations: [
      {
        id: "kumano-magaibutsu",
        name: "Kumano Magaibutsu Rock Carvings",
        type: "attraction",
        category: "hike",
        lat: 33.4782,
        lng: 131.5258,
        description: "Japan's largest rock-carved Buddhist statues — a Fudo Myoo and Dainichi Nyorai carved directly into a tuff cliff face. Reached via a steep forest path with 99 stone steps through ancient cedar trees. Deeply atmospheric and spiritually powerful.",
        kidNotes: "The forest path is steep — use a carrier for the 2-year-old. Walking sticks available at the entrance. The carvings are awe-inspiring even for young children. Allow extra time for the climb.",
        duration: "1–1.5 hours",
        priceRange: "¥300",
        url: "https://japantravel.navitime.com/en/area/jp/spot/02301-1301578/",
        tags: ["Rock Carvings", "Forest Walk", "Buddhism", "Spiritual"],
      },
      {
        id: "fuki-ji-temple",
        name: "Fuki-ji Temple",
        type: "attraction",
        category: "culture",
        lat: 33.5377,
        lng: 131.5288,
        description: "The oldest wooden building in Kyushu, built in 718 AD and designated a National Treasure. The main hall is a remarkably preserved example of Heian-period architecture set in peaceful forested grounds.",
        kidNotes: "Peaceful, spacious grounds for children to explore. The ancient wooden building is genuinely impressive. Flat approach suitable for strollers.",
        duration: "30–45 minutes",
        priceRange: "¥300",
        url: "https://japantravel.navitime.com/en/area/jp/spot/02301-1301577/",
        tags: ["Temple", "National Treasure", "Ancient", "Quiet"],
      },
      {
        id: "usa-shrine",
        name: "Usa Shrine (Usa Jingū)",
        type: "attraction",
        category: "culture",
        lat: 33.5235,
        lng: 131.3772,
        description: "An 8th-century Shinto shrine and the head of over 40,000 Hachiman shrines across Japan. Features a large compound with upper and lower shrine complexes, ponds, and ancient auxiliary buildings. One of Japan's most important shrines.",
        kidNotes: "Spacious grounds for children to explore. Many local families visit. The ponds and forested paths create a serene environment.",
        duration: "1–1.5 hours",
        priceRange: "Free",
        url: "https://www.japan-guide.com/e/e4722.html",
        tags: ["Shrine", "Historic", "Spacious Grounds"],
      },
      {
        id: "kawaraza-soba",
        name: "Kawaraza Soba",
        type: "dining",
        category: "food",
        lat: 33.57,
        lng: 131.6077,
        description: "A highly-rated soba noodle restaurant in the Kunisaki area with a wonderful rustic atmosphere. Known for excellent handmade soba and chicken tempura combinations.",
        kidNotes: "Soba noodles are generally well-received by young children. Family-friendly atmosphere. Good value for quality.",
        mealType: "Lunch",
        priceRange: "¥1,000–¥2,000",
        specialty: "Handmade soba, chicken tempura",
        tags: ["Lunch", "Soba", "Rustic"],
      },
    ],
  },

  // ─── APR 22: KUNISAKI DAY 2 ────────────────────────────────────────────────
  {
    id: "apr22",
    date: "Apr 22",
    dayLabel: "Day 8",
    title: "Farmstay & Coast",
    subtitle: "Farm life, beach play & Ruru Park",
    region: "Kunisaki, Oita",
    mapCenter: { lat: 33.55, lng: 131.45 },
    mapZoom: 11,
    heroImage: KUNISAKI_IMG,
    tips: "Enjoy the farmstay experience fully — let the kids participate in any farm activities offered. Matama Beach has very shallow, safe waters perfect for toddlers to paddle. Ruru Park is a wonderful half-day option with large playgrounds and paddle boats.",
    highlights: ["Farmstay morning activities", "Matama Beach shallow waters", "Ruru Park playground"],
    locations: [
      {
        id: "matama-beach",
        name: "Matama Beach",
        type: "attraction",
        category: "nature",
        lat: 33.6227,
        lng: 131.473,
        description: "A beautiful beach on the Kunisaki coast known for its stunning sunsets and safe shallow tidal flats. The calm, shallow waters are perfect for young children to paddle and explore. Cafés nearby for refreshments.",
        kidNotes: "Very shallow waters — completely safe for toddlers. Wide sandy beach for running and playing. Bring a change of clothes. Best visited in the afternoon for the sunset.",
        duration: "1.5–2 hours",
        priceRange: "Free",
        tags: ["Beach", "Shallow Water", "Sunset", "Toddler Safe"],
      },
      {
        id: "ruru-park",
        name: "Ruru Park (Oita Agricultural Park)",
        type: "attraction",
        category: "kids",
        lat: 33.4328,
        lng: 131.4306,
        description: "An expansive park around a lake with large-scale playground equipment, educational farm experiences, fruit orchards, and camellia gardens. Paddle boats and rental bicycles available. A wonderful family day out.",
        kidNotes: "The large playground equipment is excellent for the 4-year-old. The farm experiences and paddle boats are great for both ages. Plenty of open space for running.",
        duration: "2–3 hours",
        priceRange: "¥500–¥1,000 entry + activities",
        url: "https://oita-tourism.com/en/attractions/detail_1053.html",
        tags: ["Park", "Playground", "Farm", "Paddle Boats"],
      },
      {
        id: "kitsuki-town",
        name: "Kitsuki Castle Town Walk",
        type: "attraction",
        category: "culture",
        lat: 33.4163,
        lng: 131.6208,
        description: "A beautifully preserved castle town with samurai districts on two hills flanking a merchant valley. Narrow stone-paved lanes, white-walled samurai residences, and a small castle make this one of Kyushu's most charming historic towns.",
        kidNotes: "The lanes are flat and manageable. The castle is small and easy to explore. A lovely gentle walk through history.",
        duration: "1.5–2 hours",
        priceRange: "¥200–¥400 castle entry",
        tags: ["Castle Town", "Samurai", "Historic", "Walkable"],
      },
      {
        id: "oita-musashi",
        name: "Oita no Sora Musashi",
        type: "dining",
        category: "food",
        lat: 33.5858,
        lng: 131.7229,
        description: "A well-rated local restaurant serving delicious set meals (teishoku) with fresh local ingredients. Also functions as a farmers' market — a great place to try genuine Oita home cooking.",
        kidNotes: "Friendly, welcoming atmosphere. Set meals are generous and good value. The farmers' market section is fun to browse with kids.",
        mealType: "Lunch",
        priceRange: "¥800–¥1,500",
        specialty: "Teishoku set meals, local produce",
        tags: ["Lunch", "Set Meal", "Local", "Farmers Market"],
      },
    ],
  },

  // ─── APR 23: FERRY DAY ─────────────────────────────────────────────────────
  {
    id: "apr23",
    date: "Apr 23",
    dayLabel: "Day 9",
    title: "Ferry Home",
    subtitle: "Beppu port → overnight ferry to Osaka",
    region: "Beppu → Osaka",
    mapCenter: { lat: 33.28, lng: 131.49 },
    mapZoom: 11,
    heroImage: TOPO_BG,
    tips: "The Sunflower Ferry from Beppu to Osaka (Nanko) takes about 11–12 hours overnight. Book a Character Room (Kumamon themed!) for the kids — it makes the ferry a highlight of the trip. Children under 3 eat free for meals on board. The ferry departs in the evening, so you have the morning to explore Beppu.",
    highlights: ["Beppu Hells morning visit", "Sunflower Ferry Kumamon room", "Kids Land play area on board"],
    locations: [
      {
        id: "beppu-hells",
        name: "Beppu Jigoku (Hells of Beppu)",
        type: "attraction",
        category: "nature",
        lat: 33.3119,
        lng: 131.4989,
        description: "Beppu's famous 'hells' — a collection of dramatically coloured hot spring pools including the cobalt-blue Umi Jigoku (Sea Hell) and blood-red Chi-no-Ike Jigoku (Blood Pond Hell). Visually spectacular and educational.",
        kidNotes: "The colourful pools are visually stunning for children. All viewing areas are safely fenced. The blue and red pools are particularly dramatic. A combined ticket covers the main hells.",
        duration: "2–3 hours",
        priceRange: "¥2,200 combined ticket (free under 6)",
        url: "https://www.beppu-jigoku.com/en/",
        tags: ["Hot Springs", "Dramatic", "Colourful", "Educational"],
      },
      {
        id: "beppu-foot-bath",
        name: "Beppu Takegawara Onsen Foot Bath",
        type: "attraction",
        category: "nature",
        lat: 33.2845,
        lng: 131.4966,
        description: "A free public foot bath in central Beppu, perfect for a relaxing soak before boarding the ferry. The historic Takegawara bathhouse nearby is one of Japan's oldest.",
        kidNotes: "Free foot baths are perfect for toddlers. A gentle, relaxing experience. Good way to pass time before the evening ferry.",
        duration: "30 minutes",
        priceRange: "Free",
        tags: ["Foot Bath", "Onsen", "Free", "Relaxing"],
      },
      {
        id: "sunflower-ferry",
        name: "Sunflower Ferry (Beppu → Osaka)",
        type: "transport",
        category: "transport",
        lat: 33.2804,
        lng: 131.5067,
        description: "The MOL Sunflower Ferry runs overnight from Beppu to Osaka Nanko (arriving near Rinku Town). The large ferry has a Kids Land play area, Kumamon-themed Character Rooms, a restaurant, and a baby room. Children under 3 eat free.",
        kidNotes: "Book the Kumamon Character Room — it's a magical experience for kids. The Kids Land play area keeps children entertained. The gentle rocking of the ferry usually helps toddlers sleep well.",
        duration: "~12 hours overnight",
        priceRange: "From ¥8,000 per adult (Character Room extra)",
        url: "https://www.ferry-sunflower.co.jp/en/",
        tags: ["Ferry", "Overnight", "Kumamon Room", "Kids Land"],
      },
      {
        id: "beppu-lunch",
        name: "Beppu Toriten (Chicken Tempura) Lunch",
        type: "dining",
        category: "food",
        lat: 33.2836,
        lng: 131.4914,
        description: "Toriten — Oita's famous chicken tempura — is a must-try before leaving the region. Light, crispy chicken tempura served with ponzu dipping sauce. Available at many restaurants in central Beppu.",
        kidNotes: "Chicken tempura is universally loved by young children. Light and not too spicy. A perfect final Kyushu meal.",
        mealType: "Lunch",
        priceRange: "¥800–¥1,500",
        specialty: "Toriten (Oita chicken tempura)",
        tags: ["Lunch", "Chicken Tempura", "Local Specialty"],
      },
    ],
  },

  // ─── APR 24: DEPARTURE ─────────────────────────────────────────────────────
  {
    id: "apr24",
    date: "Apr 24",
    dayLabel: "Day 10",
    title: "Departure Day",
    subtitle: "Ferry arrives Osaka, flight home",
    region: "Rinku Town / Kansai Airport",
    mapCenter: { lat: 34.409, lng: 135.297 },
    mapZoom: 14,
    heroImage: TOPO_BG,
    tips: "The Sunflower Ferry arrives at Osaka Nanko around 8am. From Nanko, take the ferry shuttle or taxi to Rinku Town / Kansai Airport (about 45 minutes). If your flight is in the afternoon, you have time for a final visit to Rinku Park or Yu Kids before heading to the airport.",
    highlights: ["Ferry arrival morning", "Rinku Park farewell walk", "Kansai Airport kids area"],
    locations: [
      {
        id: "osaka-nanko-arrival",
        name: "Osaka Nanko Ferry Terminal",
        type: "transport",
        category: "transport",
        lat: 34.6483,
        lng: 135.4367,
        description: "The Sunflower Ferry arrives at Osaka Nanko (South Port) in the morning. From here, take a bus or taxi to Rinku Town / Kansai Airport. The journey takes about 45 minutes.",
        kidNotes: "The kids will wake up to a new port — exciting! Keep bags packed the night before for a smooth morning disembarkation.",
        duration: "Arrival ~8am",
        tags: ["Ferry Terminal", "Arrival", "Transport"],
      },
      {
        id: "rinku-park-farewell",
        name: "Rinku Park (Final Morning)",
        type: "attraction",
        category: "nature",
        lat: 34.4091,
        lng: 135.2977,
        description: "A final stroll through Rinku Park before the flight — watching the planes take off from Kansai Airport across the bay is a perfect way to end the trip. The marble beach and open lawns give the kids one last run.",
        kidNotes: "A relaxed, low-key final activity. Plane spotting is a great way to get kids excited about the upcoming flight home.",
        duration: "1 hour",
        priceRange: "Free",
        tags: ["Park", "Farewell", "Plane Spotting"],
      },
      {
        id: "kia-kids-area",
        name: "Kansai Airport Kids Play Area",
        type: "attraction",
        category: "kids",
        lat: 34.4338,
        lng: 135.2263,
        description: "Colourful children's play areas located within Kansai International Airport, designed for kids up to 6 years old. A perfect way to burn energy before boarding the flight home.",
        kidNotes: "Supervised play area inside the terminal. Parents must accompany children. Great for burning off final energy before the flight.",
        duration: "30 min–1 hour",
        priceRange: "Free",
        url: "https://www.kansai-airport.or.jp/en/service/child/kidscorner",
        tags: ["Airport", "Play Area", "Free", "Pre-flight"],
      },
      {
        id: "rinku-breakfast",
        name: "Rinku Food Park (Breakfast)",
        type: "dining",
        category: "food",
        lat: 34.4063,
        lng: 135.2959,
        description: "A bright, welcoming food court at Rinku Premium Outlets with diverse breakfast options — Japanese, Western, and Korean. 513 seats, perfect for families. A good final meal before the flight.",
        kidNotes: "Multiple options for different tastes. High chairs available. Convenient location near the airport.",
        mealType: "Breakfast",
        priceRange: "¥600–¥1,200",
        tags: ["Breakfast", "Food Court", "Pre-flight"],
      },
    ],
  },
];

export const categoryColors: Record<Category, string> = {
  nature: "#2D5016",
  culture: "#4A3728",
  food: "#C4622D",
  kids: "#1A6B8A",
  transport: "#5A5A7A",
  accommodation: "#7B4A8A",
  hike: "#5A7A2D",
};

export const categoryLabels: Record<Category, string> = {
  nature: "Nature",
  culture: "Culture",
  food: "Dining",
  kids: "Kids",
  transport: "Transport",
  accommodation: "Stay",
  hike: "Hike",
};

export const categoryEmoji: Record<Category, string> = {
  nature: "🌿",
  culture: "⛩️",
  food: "🍜",
  kids: "🎠",
  transport: "🚢",
  accommodation: "🏨",
  hike: "🥾",
};
