// Kyushu Family Trip 2026 — Itinerary Data
// Design: Topographic Field Journal — earthy palette, cartographic aesthetic
// All coordinates verified for accuracy

export type LocationType = "attraction" | "dining" | "transport" | "accommodation";
export type Category = "nature" | "culture" | "food" | "kids" | "transport" | "accommodation" | "hike";

export interface Location {
  id: string;
  name: string;
  type: LocationType;
  category: Category;
  lat: number;
  lng: number;
  description: string;
  kidNotes?: string;
  duration?: string;
  priceRange?: string;
  specialty?: string;
  mealType?: string;
  url?: string;
  tips?: string;
  tags?: string[];
  isOption?: boolean; // multiple options for same slot
  optionGroup?: string; // group name for options
}

export interface DayItinerary {
  id: string;
  date: string;
  dayLabel: string;
  title: string;
  subtitle: string;
  region: string;
  mapCenter: { lat: number; lng: number };
  mapZoom: number;
  heroImage?: string;
  locations: Location[];
  tips: string;
  highlights: string[];
}

const TOPO_BG = "https://d2xsxph8kpxj0f.cloudfront.net/310519663274163203/jRjLAkDKU7GLkhJ5u839XZ/kyushu-topo-bg-iyU5owaEVJCB8g3Ayh6oxC.webp";
const ASO_IMG = "https://d2xsxph8kpxj0f.cloudfront.net/310519663274163203/jRjLAkDKU7GLkhJ5u839XZ/kyushu-aso-volcano-nZ7KtmXk2xLu5qfFfi9qcq.webp";
const KUNISAKI_IMG = "https://d2xsxph8kpxj0f.cloudfront.net/310519663274163203/jRjLAkDKU7GLkhJ5u839XZ/kyushu-kunisaki-bdNqSPmQKQuveA5zW3ftMh.webp";

export const itinerary: DayItinerary[] = [
  // ─── APR 15: ARRIVAL ───────────────────────────────────────────────────────
  {
    id: "apr15",
    date: "Apr 15",
    dayLabel: "Day 1",
    title: "Arrival at Kansai",
    subtitle: "Fly in, collect Shinkansen tickets & settle in at Rinku Town",
    region: "Osaka / Rinku Town",
    mapCenter: { lat: 34.434, lng: 135.232 },
    mapZoom: 13,
    heroImage: TOPO_BG,
    tips: "Depart Singapore at 8:40am. Arrive KIX at 4:10pm. Pick up your Shinkansen ticket from JR Kansai Airport Station on arrival — you'll need it tomorrow. Take the train one stop to Rinku-Town Station (Exit 5) and get your ICOCA card. Dinner is at OMO Dining (6–9pm) in the hotel. Buy milk and snacks from the Lawson inside the hotel.",
    highlights: ["Collect Shinkansen tickets at KIX", "ICOCA card pick-up", "Dinner at OMO Dining"],
    locations: [
      {
        id: "kix-arrival",
        name: "Kansai International Airport (KIX)",
        type: "transport",
        category: "transport",
        lat: 34.4338,
        lng: 135.2441,
        description: "Arrive at 4:10pm. Head to JR Kansai Airport Station to pick up your pre-booked Shinkansen tickets. Also pick up ICOCA cards here for convenient rail travel throughout the trip.",
        kidNotes: "After a long flight, keep things simple — just collect tickets and head to the hotel. The station is inside the terminal building.",
        tags: ["Arrival", "Transport", "Shinkansen Tickets", "ICOCA"],
      },
      {
        id: "rinku-town-station",
        name: "Rinku-Town Station",
        type: "transport",
        category: "transport",
        lat: 34.4091,
        lng: 135.2977,
        description: "Take the train one stop from KIX to Rinku-Town Station. Use Exit 5. The OMO Kansai Airport hotel is a short walk from here.",
        kidNotes: "Just one stop on the train — very easy with tired kids and luggage.",
        tags: ["Transport", "Train", "Rinku Town"],
      },
      {
        id: "omo-kansai",
        name: "OMO Kansai Airport Hotel",
        type: "accommodation",
        category: "accommodation",
        lat: 34.4338,
        lng: 135.2263,
        description: "Your base for the first and last nights — a Hoshino Resorts property near Kansai Airport. Check in and settle in after the flight. There is a Lawson convenience store inside the hotel for milk and snacks.",
        kidNotes: "Very convenient for families — no long transfers after landing. Stock up on milk and snacks at the in-hotel Lawson.",
        tags: ["Accommodation", "Airport", "Hoshino Resorts"],
      },
      {
        id: "omo-dining-day1",
        name: "OMO Dining",
        type: "dining",
        category: "food",
        lat: 34.4338,
        lng: 135.2263,
        description: "Dinner at the hotel restaurant, OMO Dining, open 6–9pm. A convenient and relaxed option after a long travel day.",
        kidNotes: "Dinner in the hotel means no extra travel after a tiring flight day. Great for the kids.",
        mealType: "Dinner",
        tags: ["Dinner", "Hotel Restaurant"],
      },
    ],
  },

  // ─── APR 16: KUMAMOTO ──────────────────────────────────────────────────────
  {
    id: "apr16",
    date: "Apr 16",
    dayLabel: "Day 2",
    title: "Kumamoto City",
    subtitle: "Shinkansen south, castle visit, then drive to Hakushu",
    region: "Kumamoto City → Hakushu",
    mapCenter: { lat: 32.803, lng: 130.706 },
    mapZoom: 13,
    heroImage: TOPO_BG,
    tips: "Breakfast buffet at OMO Dining (6–10am). A Klook driver is booked at 8:15am to Shin-Osaka Station. Buy lunch before boarding the Shinkansen. Take Shinkansen Mizuho 607 at 9:54am, arriving Kumamoto at 12:59pm. Buy diapers from Drug Eleven in Higo Yokamon Market at Kumamoto Station. Collect the rental car, then visit Kumamoto Castle (open 9am–5pm, last admission 4:30pm for main castle). Dinner options: Konbini or Katsuretsu Tei Shinshigai in Sunroad Shinshigai near the castle. Pick up milk, breakfast and snacks from a Konbini before driving to Hakushu (about 1.5 hours).",
    highlights: ["Shinkansen Mizuho 607 from Shin-Osaka", "Kumamoto Castle", "Drive to Hakushu"],
    locations: [
      {
        id: "shin-osaka-station",
        name: "Shin-Osaka Station",
        type: "transport",
        category: "transport",
        lat: 34.7334,
        lng: 135.5001,
        description: "Klook driver picks up at 8:15am. Buy lunch bento before boarding. Board Shinkansen Mizuho 607 at 9:54am bound for Kumamoto.",
        kidNotes: "Buy lunch bento at the station before boarding — the kids will enjoy eating on the Shinkansen.",
        tags: ["Shinkansen", "Transport", "Shin-Osaka"],
      },
      {
        id: "kumamoto-station",
        name: "Kumamoto Station",
        type: "transport",
        category: "transport",
        lat: 32.7936,
        lng: 130.6987,
        description: "Arrive at 12:59pm. Head to Drug Eleven in Higo Yokamon Market inside the station to buy diapers. Then collect the rental car.",
        kidNotes: "Stock up on diapers at Drug Eleven in the station before picking up the car.",
        tags: ["Arrival", "Car Rental", "Kumamoto"],
      },
      {
        id: "kumamoto-castle",
        name: "Kumamoto Castle",
        type: "attraction",
        category: "culture",
        lat: 32.8061,
        lng: 130.706,
        description: "One of Japan's three great castles, known for its dramatic stone walls and imposing black keep. Open 9am–5pm; last admission to the main castle is 4:30pm (other areas 4pm). The castle and grounds are stroller-friendly with elevators available.",
        kidNotes: "Strollers allowed throughout. Elevators available. The wide castle grounds give kids plenty of space to roam.",
        duration: "1.5–2 hours",
        priceRange: "¥800 adults, free under 6",
        url: "https://castle.kumamoto-guide.jp/en/info/",
        tags: ["Castle", "History", "Stroller Friendly"],
      },
      {
        id: "katsuretsu-tei",
        name: "Katsuretsu Tei Shinshigai",
        type: "dining",
        category: "food",
        lat: 32.8018,
        lng: 130.7073,
        description: "A tonkatsu restaurant in Sunroad Shinshigai shopping arcade, near Kumamoto Castle. A good dinner option before the drive to Hakushu. Alternatively, grab dinner from a nearby Konbini.",
        kidNotes: "Sunroad Shinshigai is also a great place to pick up milk, breakfast items and snacks from a Konbini for the next few days in Hakushu.",
        mealType: "Dinner",
        priceRange: "¥1,000–¥2,000",
        tags: ["Dinner", "Tonkatsu", "Arcade"],
        isOption: true,
        optionGroup: "apr16-dinner",
      },
      {
        id: "hakushu-drive",
        name: "Drive to Hakushu",
        type: "transport",
        category: "transport",
        lat: 32.9336,
        lng: 131.0701,
        description: "Drive from Kumamoto to the Hakushu / Minami Aso area — approximately 1.5 hours. This is your base for the next four nights.",
        kidNotes: "A scenic evening drive through the Aso countryside. Kids may nap on the way.",
        duration: "~1.5 hours",
        tags: ["Drive", "Transport", "Hakushu"],
      },
    ],
  },

  // ─── APR 17: TAKACHIHO & STRAWBERRY PICKING ────────────────────────────────
  {
    id: "apr17",
    date: "Apr 17",
    dayLabel: "Day 3",
    title: "Takachiho & Strawberry Picking",
    subtitle: "Gorge, railway, and afternoon at the farm",
    region: "Takachiho / Minami Aso",
    mapCenter: { lat: 32.71, lng: 131.31 },
    mapZoom: 10,
    heroImage: ASO_IMG,
    tips: "Breakfast in Hakushu or on the car. Leave at 7:45am for the 1.5-hour drive to Takachiho. Ride the Takachiho Amaterasu Railway (9:40am or 11am departures). Then visit Takachiho Gorge — use the Oshioi or Araragi Parking Lot. Lunch option: Cafe Takachiho Base (bigger area but limited menu). Drive back to Aso area (about 1 hour 10 min to Minami Aso). Afternoon: strawberry picking at Aso Kenkou Nouen Farm (3pm booking, open 9am–5pm). Stop by a takoyaki or manju place near Minami Aso. Get groceries on the way back for dinner.",
    highlights: ["Takachiho Amaterasu Railway", "Takachiho Gorge", "Strawberry picking at Aso Kenkou Nouen Farm"],
    locations: [
      {
        id: "takachiho-railway",
        name: "Takachiho Amaterasu Railway",
        type: "attraction",
        category: "kids",
        lat: 32.7008,
        lng: 131.3083,
        description: "A scenic open-air Super Cart railway running along a former rail line through the Takachiho highlands. Departures at 9:40am and 11am (among others). A 10-minute walk from Takachiho Bus Center. Closed on the 3rd Thursday of every month.",
        kidNotes: "Kids love the open-air carts and the dramatic views. Buy tickets at the station. A 10-minute walk from Takachiho Bus Center.",
        duration: "30 minutes",
        priceRange: "¥2,000 per adult, ¥700 per child",
        url: "https://www.amaterasu-railway.jp/",
        tags: ["Railway", "Scenic", "Kids Love"],
      },
      {
        id: "takachiho-gorge",
        name: "Takachiho Gorge",
        type: "attraction",
        category: "hike",
        lat: 32.7072,
        lng: 131.3058,
        description: "A dramatic gorge carved by the Gokase River through columnar basalt cliffs, with the beautiful Manai Falls at its heart. Use the Oshioi Parking Lot or Araragi Parking Lot (southern end) for closer, flatter access to restaurants, shops, and the viewing deck.",
        kidNotes: "The walking path along the gorge is paved. Use the Araragi Parking Lot for easier access. The waterfall is spectacular.",
        duration: "1–1.5 hours",
        priceRange: "Free (boat rental ¥2,000/30 min)",
        url: "https://takachiho-kanko.info/en/sightseeing/takachihogorge.php",
        tags: ["Gorge", "Waterfall", "Scenic"],
      },
      {
        id: "cafe-takachiho-base",
        name: "Cafe Takachiho Base",
        type: "dining",
        category: "food",
        lat: 32.7065,
        lng: 131.3052,
        description: "A lunch option near Takachiho Gorge with a bigger seating area, though the menu options are more limited. A convenient stop before heading back to Aso.",
        kidNotes: "Spacious seating is helpful with young children. Check the menu before committing.",
        mealType: "Lunch",
        tags: ["Lunch", "Cafe", "Takachiho"],
        isOption: true,
        optionGroup: "apr17-lunch",
      },
      {
        id: "aso-kenkou-nouen",
        name: "Aso Kenkou Nouen Farm (Strawberry Picking)",
        type: "attraction",
        category: "kids",
        lat: 32.8208,
        lng: 130.9972,
        description: "Strawberry picking at this farm in the Minami Aso area. Booked for 3pm. Open 9am–5pm. A wonderful hands-on experience for the kids in the beautiful Aso countryside.",
        kidNotes: "Strawberry picking is a huge hit with young children. Arrive on time for your 3pm booking.",
        duration: "1–1.5 hours",
        tags: ["Strawberry Picking", "Farm", "Kids", "Booking Required"],
      },
    ],
  },

  // ─── APR 18: ASO OBSERVATORIES & LOCAL EXPLORE ─────────────────────────────
  {
    id: "apr18",
    date: "Apr 18",
    dayLabel: "Day 4",
    title: "Milk Road & Kikuchi",
    subtitle: "Observatories, gorge, donuts and laundry day",
    region: "Aso / Kikuchi",
    mapCenter: { lat: 32.96, lng: 131.05 },
    mapZoom: 11,
    heroImage: ASO_IMG,
    tips: "Breakfast in Hakushu. Morning BSF call for Jerlene 8am–10am (Japan time). Morning options: drive Milk Road and visit observatories (Kabutoiwa, Nishiyunouraenchi, Aso Skyline), or head to Kikuchi Gorge and Kikuchi Castle. Lunch in Kikuchi area. Afternoon nap in the Airbnb. Visit Marugo Donuts (open 11am–5pm). Laundry day. Optional: Takamori Tunnel Museum.",
    highlights: ["Milk Road observatories", "Kikuchi Gorge", "Marugo Donuts"],
    locations: [
      {
        id: "milk-road-observatories",
        name: "Milk Road Observatories",
        type: "attraction",
        category: "nature",
        lat: 32.9654,
        lng: 131.0845,
        description: "A scenic highland road across the Aso caldera with several observation points offering sweeping views. Key stops include Kabutoiwa Observatory, Nishiyunouraenchi Observatory, and Aso Skyline Observatory.",
        kidNotes: "Easy roadside stops with dramatic views. Can be windy — dress the kids warmly.",
        duration: "1–2 hours",
        priceRange: "Free",
        tags: ["Viewpoint", "Scenic Drive", "Aso Caldera"],
        isOption: true,
        optionGroup: "apr18-morning",
      },
      {
        id: "kikuchi-gorge",
        name: "Kikuchi Gorge",
        type: "attraction",
        category: "hike",
        lat: 33.0572,
        lng: 130.9811,
        description: "A beautiful forested gorge with clear mountain streams, mossy rocks, and a well-maintained walking trail. One of Japan's top 100 forests. Especially lovely in spring with fresh green foliage.",
        kidNotes: "The trail is mostly flat and well-paved near the entrance. Cool and shaded — great on a warm day.",
        duration: "1–1.5 hours",
        priceRange: "Free",
        tags: ["Gorge", "Forest Walk", "Nature"],
        isOption: true,
        optionGroup: "apr18-morning",
      },
      {
        id: "kikuchi-castle",
        name: "Kikuchi Castle",
        type: "attraction",
        category: "culture",
        lat: 33.0606,
        lng: 130.9748,
        description: "The reconstructed castle of the Kikuchi clan, set on a forested hill with panoramic views of the surrounding countryside. A quiet, atmospheric site with historical significance.",
        kidNotes: "A short walk up to the castle. Good views from the top. Combine with Kikuchi Gorge for a half-day outing.",
        duration: "30–45 minutes",
        priceRange: "Free",
        tags: ["Castle", "History", "Views"],
        isOption: true,
        optionGroup: "apr18-morning",
      },
      {
        id: "marugo-donuts",
        name: "Marugo Donuts",
        type: "dining",
        category: "food",
        lat: 32.9336,
        lng: 131.0701,
        description: "A popular local donut shop in the Aso area, open 11am–5pm. Known for fluffy, freshly made donuts. A perfect afternoon treat.",
        kidNotes: "Kids love donuts! Go before they sell out — they can be popular on weekends.",
        duration: "15–30 minutes",
        mealType: "Snack",
        tags: ["Donuts", "Snack", "Local"],
      },
      {
        id: "takamori-tunnel-museum",
        name: "Takamori Tunnel Museum",
        type: "attraction",
        category: "culture",
        lat: 32.8208,
        lng: 131.1,
        description: "A unique museum housed inside a former railway tunnel in Takamori. Features local history exhibits and a cool, atmospheric tunnel environment.",
        kidNotes: "An interesting and unusual experience inside a real tunnel. Cool temperatures inside — bring a light layer.",
        duration: "30–45 minutes",
        tags: ["Museum", "Tunnel", "Unique"],
        isOption: true,
        optionGroup: "apr18-afternoon",
      },
    ],
  },

  // ─── APR 19: NAKADAKE CRATER & KUSASENRI ───────────────────────────────────
  {
    id: "apr19",
    date: "Apr 19",
    dayLabel: "Day 5",
    title: "Into the Volcano",
    subtitle: "Nakadake Crater, Kusasenri meadow and Daikanbo",
    region: "Aso, Kumamoto",
    mapCenter: { lat: 32.88, lng: 131.07 },
    mapZoom: 11,
    heroImage: ASO_IMG,
    tips: "Breakfast in Hakushu. Morning: drive up to Nakadake Crater from Aso Sanjo Terminal — check the volcanic alert level and weather before going, and bring masks. Visit Kusasenri Grassland (Kusasenri Parking Lot) and hike Kishimadake (paved steps, 1.4km) or the Kusasenri Grassland–Furubochu Walking Trail. See Komezuka (the little volcano). Lunch at Soba Dojo (opens 10am). Afternoon nap in the Airbnb. Then visit Uchinomaki Family Park (Aso Viva) and Daikanbo viewpoint.",
    highlights: ["Nakadake Crater (weather permitting)", "Kusasenri Grassland meadow", "Daikanbo panoramic viewpoint"],
    locations: [
      {
        id: "nakadake-crater",
        name: "Nakadake Crater",
        type: "attraction",
        category: "nature",
        lat: 32.8847,
        lng: 131.0869,
        description: "Drive up to the active Nakadake Crater from Aso Sanjo Terminal. Access depends on the volcanic alert level — check before going. Bring masks as volcanic gases can be present. One of the few places in the world where you can get close to an active volcano.",
        kidNotes: "Check the volcanic alert level before heading up. Bring masks for the kids. If access is restricted, Kusasenri meadow below is a wonderful alternative.",
        duration: "30–45 minutes",
        priceRange: "Free (parking fee applies)",
        tags: ["Volcano", "Active Crater", "Unique", "Weather Dependent"],
      },
      {
        id: "kusasenri",
        name: "Kusasenri Grassland",
        type: "attraction",
        category: "hike",
        lat: 32.8847,
        lng: 131.0551,
        description: "A perfectly circular ancient crater about 1km across, now a sweeping grassland with two shallow ponds. Horses graze freely across the meadow. In April the grass is fresh green. Hike Kishimadake (paved steps, 1.4km) or the Kusasenri Grassland–Furubochu Walking Trail.",
        kidNotes: "Completely flat — perfect for toddlers to walk and run freely. Seeing the grazing horses up close is magical for young children.",
        duration: "45 min–1 hour",
        priceRange: "Free (parking ¥300)",
        tags: ["Meadow", "Easy Walk", "Horses", "Nature"],
      },
      {
        id: "komezuka",
        name: "Komezuka",
        type: "attraction",
        category: "nature",
        lat: 32.9054,
        lng: 131.0358,
        description: "A perfectly cone-shaped small parasitic volcano rising from the Aso caldera floor. One of the most photogenic sights in Aso — it looks like an upturned rice bowl (its name means 'rice mound').",
        kidNotes: "A quick and easy stop. The perfect cone shape is fascinating for children. Great photo opportunity.",
        duration: "15–20 minutes",
        priceRange: "Free",
        tags: ["Volcano", "Scenic", "Photo Stop"],
      },
      {
        id: "soba-dojo",
        name: "Soba Dojo",
        type: "dining",
        category: "food",
        lat: 32.9336,
        lng: 131.0701,
        description: "A local soba restaurant in the Aso area, open from 10am. A good lunch stop after the morning volcano activities.",
        kidNotes: "Soba noodles are generally well-received by young children. Opens early at 10am — good for an early lunch.",
        mealType: "Lunch",
        tags: ["Lunch", "Soba", "Local"],
      },
      {
        id: "aso-viva",
        name: "Uchinomaki Family Park (Aso Viva)",
        type: "attraction",
        category: "kids",
        lat: 32.9475,
        lng: 131.1358,
        description: "A family park in the Uchinomaki hot spring town area, great for children with play equipment and open spaces.",
        kidNotes: "A relaxed afternoon activity for the kids after their nap. Open spaces for running around.",
        duration: "1–1.5 hours",
        tags: ["Park", "Kids", "Playground"],
      },
      {
        id: "daikanbo",
        name: "Daikanbo Viewpoint",
        type: "attraction",
        category: "nature",
        lat: 32.9654,
        lng: 131.0845,
        description: "The most dramatic viewpoint on the Aso caldera's northeast rim. From here you can see all five Aso peaks lined up across the vast caldera floor — one of Japan's most spectacular panoramas.",
        kidNotes: "Very easy to access from the parking area — just a short walk to the viewpoint. Can be windy, so dress toddlers warmly.",
        duration: "20–30 minutes",
        priceRange: "Free",
        tags: ["Viewpoint", "Volcano", "Panorama"],
      },
    ],
  },

  // ─── APR 20: KUJU & FARMSTAY ────────────────────────────────────────────────
  {
    id: "apr20",
    date: "Apr 20",
    dayLabel: "Day 6",
    title: "Kuju Highlands & Farmstay",
    subtitle: "Chojabaru boardwalk, suspension bridge, then farmstay",
    region: "Kuju / Oita",
    mapCenter: { lat: 33.1, lng: 131.23 },
    mapZoom: 11,
    heroImage: ASO_IMG,
    tips: "Breakfast in Hakushu. Check out by 10am. Drive to Chojabaru Visitor's Centre / Tadewara Marsh boardwalk (about 1 hour). Then visit Kuju Yume Otsuribashi suspension bridge (Kokonoe Yume Otsuribashi). Lunch options: Kasuga Udon (30 min from Chojabaru) or Restaurant Aoyama (has a Lawson next door — good for buying breakfast and snacks for the farmstay). Drive to the farmstay (about 1 hour). Dinner in the farmstay.",
    highlights: ["Chojabaru Boardwalk & Tadewara Marsh", "Kokonoe Yume Otsuribashi suspension bridge", "Farmstay arrival"],
    locations: [
      {
        id: "chojabaru-boardwalk",
        name: "Chojabaru Visitor's Centre & Tadewara Marsh",
        type: "attraction",
        category: "hike",
        lat: 33.1,
        lng: 131.25,
        description: "A scenic wetland boardwalk through Tadewara Marsh in the Kuju highlands. The Chojabaru Visitor's Centre provides information on the local flora and fauna. The boardwalk takes about 45 minutes and is free of charge.",
        kidNotes: "The flat boardwalk is easy for young children. The wetland scenery is beautiful and peaceful.",
        duration: "45 minutes",
        priceRange: "Free",
        tags: ["Boardwalk", "Wetland", "Nature", "Free"],
      },
      {
        id: "kokonoe-suspension-bridge",
        name: "Kokonoe Yume Otsuribashi (Suspension Bridge)",
        type: "attraction",
        category: "nature",
        lat: 33.0833,
        lng: 131.1833,
        description: "One of Japan's longest pedestrian suspension bridges, stretching 390 metres across a dramatic gorge with views of two waterfalls. A thrilling and memorable experience.",
        kidNotes: "The bridge can sway — some young children may find it exciting or a little scary. The views are spectacular. Hold hands!",
        duration: "30 minutes",
        priceRange: "¥500 adults, free for preschoolers",
        tags: ["Suspension Bridge", "Gorge", "Views", "Thrilling"],
      },
      {
        id: "kasuga-udon",
        name: "Kasuga Udon",
        type: "dining",
        category: "food",
        lat: 33.07,
        lng: 131.22,
        description: "A local udon restaurant about 30 minutes from Chojabaru and the suspension bridge. A good lunch stop on the way to the farmstay.",
        kidNotes: "Udon is a reliable crowd-pleaser for young children.",
        mealType: "Lunch",
        tags: ["Lunch", "Udon", "Local"],
        isOption: true,
        optionGroup: "apr20-lunch",
      },
      {
        id: "restaurant-aoyama",
        name: "Restaurant Aoyama",
        type: "dining",
        category: "food",
        lat: 33.08,
        lng: 131.2,
        description: "A restaurant with a Lawson convenience store next door — ideal for buying breakfast and snacks for the farmstay while having lunch here.",
        kidNotes: "Stock up on breakfast items and snacks at the adjacent Lawson for the farmstay days.",
        mealType: "Lunch",
        tags: ["Lunch", "Convenience Store Nearby"],
        isOption: true,
        optionGroup: "apr20-lunch",
      },
      {
        id: "farmstay-arrival",
        name: "Farmstay",
        type: "accommodation",
        category: "accommodation",
        lat: 33.15,
        lng: 131.35,
        description: "Your farmstay base for two nights in the Oita countryside. Dinner is provided in the farmstay. Enjoy the rural setting and slower pace of life.",
        kidNotes: "A wonderful change of pace for the kids — open spaces, farm animals, and fresh country air.",
        tags: ["Farmstay", "Accommodation", "Rural"],
      },
    ],
  },

  // ─── APR 21: FARMSTAY DAY ──────────────────────────────────────────────────
  {
    id: "apr21",
    date: "Apr 21",
    dayLabel: "Day 7",
    title: "Farmstay Day",
    subtitle: "Slow morning, farm life, and a relaxed day",
    region: "Oita Countryside",
    mapCenter: { lat: 33.15, lng: 131.35 },
    mapZoom: 12,
    heroImage: KUNISAKI_IMG,
    tips: "Breakfast in the farmstay (own breakfast). A relaxed day at the farmstay — enjoy the farm activities and open countryside. Lunch in the farmstay. Afternoon nap. Dinner in the farmstay. Jerlene BSF 8:50pm–10:30pm (Japan time).",
    highlights: ["Farm activities", "Relaxed countryside day", "Farmstay meals"],
    locations: [
      {
        id: "farmstay-day",
        name: "Farmstay",
        type: "accommodation",
        category: "accommodation",
        lat: 33.15,
        lng: 131.35,
        description: "A full day at the farmstay. Enjoy the farm environment, open spaces, and the slower pace of rural Oita. All meals are at the farmstay. Dinner is followed by Jerlene's BSF session at 8:50pm–10:30pm Japan time.",
        kidNotes: "Let the kids explore the farm freely. A wonderful break from sightseeing — just enjoy the countryside.",
        tags: ["Farmstay", "Rest Day", "Farm Life"],
      },
    ],
  },

  // ─── APR 22: SAFARI & FERRY ─────────────────────────────────────────────────
  {
    id: "apr22",
    date: "Apr 22",
    dayLabel: "Day 8",
    title: "African Safari & Ferry",
    subtitle: "Wildlife safari, Beppu Ropeway, then overnight ferry",
    region: "Oita / Beppu",
    mapCenter: { lat: 33.28, lng: 131.49 },
    mapZoom: 11,
    heroImage: KUNISAKI_IMG,
    tips: "Breakfast in the farmstay. Check out by 10am. Drive to Kyushu Wildlife Park African Safari (51 min). Reception opens 8:50am, park opens 9:15am. Lunch at Family Restaurant Salvia at the safari. Afternoon: Jumonji Viewpoint or Beppu Ropeway. Buy provisions for the ferry (breakfast for next day) from Lawson or Family Mart near the ferry terminal. Chux drops everyone and luggage at Sunflower terminal, returns car at Nissan, and walks over (10–15 min walk). Ferry check-in at 5:45pm. Dinner on the ferry (buffet 5:45–9pm). Ferry departs 6:45pm.",
    highlights: ["Kyushu Wildlife Park African Safari", "Beppu Ropeway", "Sunflower Ferry overnight"],
    locations: [
      {
        id: "african-safari",
        name: "Kyushu Wildlife Park African Safari",
        type: "attraction",
        category: "kids",
        lat: 33.3119,
        lng: 131.4989,
        description: "A drive-through wildlife safari park where you can see lions, elephants, giraffes, and more from your car. The 30–40 minute self-drive circuit is a thrilling experience. Reception opens at 8:50am, park opens at 9:15am.",
        kidNotes: "An incredible experience for young children — seeing wild animals up close from the car. Absolutely do not open the windows near the big cats!",
        duration: "2–3 hours",
        priceRange: "¥2,600 adults, ¥1,500 children 4yo and up",
        tags: ["Safari", "Animals", "Kids Favourite", "Drive-through"],
      },
      {
        id: "salvia-restaurant",
        name: "Family Restaurant Salvia (at the Safari)",
        type: "dining",
        category: "food",
        lat: 33.3119,
        lng: 131.4989,
        description: "The family restaurant inside the African Safari park. A convenient lunch option after the safari drive.",
        kidNotes: "Convenient to eat at the park and avoid extra driving with tired kids.",
        mealType: "Lunch",
        tags: ["Lunch", "Safari Restaurant"],
        isOption: true,
        optionGroup: "apr22-lunch",
      },
      {
        id: "beppu-ropeway",
        name: "Beppu Ropeway",
        type: "attraction",
        category: "nature",
        lat: 33.2836,
        lng: 131.4914,
        description: "A cable car ascending Mt. Tsurumi offering panoramic views over Beppu Bay and the city below. A scenic afternoon activity before heading to the ferry terminal.",
        kidNotes: "Kids enjoy the cable car ride. The views from the top are spectacular. Dress warmly — it can be cool at the summit.",
        duration: "1–1.5 hours",
        priceRange: "¥1,800 adults (roundtrip), ¥900 children 4yo and up",
        tags: ["Ropeway", "Views", "Scenic"],
        isOption: true,
        optionGroup: "apr22-afternoon",
      },
      {
        id: "jumonji-viewpoint",
        name: "Jumonji Viewpoint",
        type: "attraction",
        category: "nature",
        lat: 33.2804,
        lng: 131.4967,
        description: "A scenic viewpoint overlooking Beppu Bay and the surrounding mountains. A quick stop for panoramic views before the ferry.",
        kidNotes: "A quick and easy stop with great views. Good for a final photo of the Kyushu landscape.",
        duration: "15–20 minutes",
        priceRange: "Free",
        tags: ["Viewpoint", "Beppu", "Scenic"],
        isOption: true,
        optionGroup: "apr22-afternoon",
      },
      {
        id: "sunflower-ferry",
        name: "Sunflower Ferry (Beppu → Osaka)",
        type: "transport",
        category: "transport",
        lat: 33.2804,
        lng: 131.5067,
        description: "Check in to the ferry at 5:45pm at Sunflower terminal. Chux drops everyone and luggage at the terminal, returns the rental car at Nissan, and walks over (10–15 min). Dinner buffet on board 5:45–9pm. Ferry departs at 6:45pm. Buy provisions (breakfast for next day) from Lawson or Family Mart near the terminal before boarding.",
        kidNotes: "The ferry has a Kids Land play area. The gentle rocking usually helps toddlers sleep well. Stock up on breakfast items before boarding.",
        duration: "~12 hours overnight",
        priceRange: "From ¥8,000 per adult",
        url: "https://www.ferry-sunflower.co.jp/en/",
        tags: ["Ferry", "Overnight", "Beppu", "Departure 6:45pm"],
      },
    ],
  },

  // ─── APR 23: FERRY ARRIVAL & RINKU ─────────────────────────────────────────
  {
    id: "apr23",
    date: "Apr 23",
    dayLabel: "Day 9",
    title: "Ferry Arrival & Rinku",
    subtitle: "Morning arrival, Rinku Park, Ferris Wheel & outlets",
    region: "Rinku Town / Osaka",
    mapCenter: { lat: 34.409, lng: 135.297 },
    mapZoom: 13,
    heroImage: TOPO_BG,
    tips: "Ferry arrives at 6:35am. Breakfast on the ferry (5:30–6:15am) or buy from the conbini at the ferry terminal. Klook driver picks up at 7:30am. Travel to OMO Kansai Airport hotel — drop off baggage and check for early check-in. Morning activities: Rinku Park, Rinku no Hoshi Ferris Wheel at Rinku Pleasure Town Seacle, Rinku Premium Outlet Mall, or Don Quijote. Lunch in Rinku. Afternoon hotel nap. Dinner at OMO Dining (6–9pm) or in the area.",
    highlights: ["Ferry arrives 6:35am", "Rinku Park", "Rinku no Hoshi Ferris Wheel", "Rinku Premium Outlets"],
    locations: [
      {
        id: "ferry-arrival",
        name: "Ferry Arrival",
        type: "transport",
        category: "transport",
        lat: 34.6483,
        lng: 135.4367,
        description: "The Sunflower Ferry arrives at 6:35am. Breakfast is served on board from 5:30–6:15am, or buy from the conbini at the ferry terminal on arrival.",
        kidNotes: "Wake the kids up for breakfast on the ferry before arrival. Keep bags packed the night before for a smooth morning.",
        duration: "Arrival 6:35am",
        tags: ["Ferry Arrival", "Transport"],
      },
      {
        id: "klook-driver-day9",
        name: "Klook Driver Pickup (7:30am)",
        type: "transport",
        category: "transport",
        lat: 34.6483,
        lng: 135.4367,
        description: "Booked Klook driver picks up at 7:30am from the ferry terminal. Travel to OMO Kansai Airport hotel to drop off baggage and check for early check-in.",
        kidNotes: "A private driver means no struggling with luggage and tired kids on public transport.",
        tags: ["Transport", "Klook Driver", "Private Transfer"],
      },
      {
        id: "omo-kansai-day9",
        name: "OMO Kansai Airport Hotel",
        type: "accommodation",
        category: "accommodation",
        lat: 34.4338,
        lng: 135.2263,
        description: "Drop off baggage and check for early check-in. Your base for the final night before flying home.",
        kidNotes: "Drop the bags and head out — check-in may not be available until the afternoon.",
        tags: ["Accommodation", "Baggage Drop"],
      },
      {
        id: "rinku-park",
        name: "Rinku Park",
        type: "attraction",
        category: "nature",
        lat: 34.4091,
        lng: 135.2977,
        description: "A vast waterside park with sweeping views of Kansai International Airport across the bay. Features Marble Beach (smooth pebbles), a fountain garden, and wide open lawns. Perfect for watching planes take off and land.",
        kidNotes: "Huge open space for toddlers to run freely. Plane spotting is a big hit with young kids. The pebble beach is a fun sensory experience.",
        duration: "1–2 hours",
        url: "https://rinku.osaka-park.or.jp/english",
        tags: ["Park", "Plane Spotting", "Beach"],
      },
      {
        id: "rinku-ferris",
        name: "Rinku no Hoshi Ferris Wheel",
        type: "attraction",
        category: "kids",
        lat: 34.4088,
        lng: 135.2974,
        description: "An 85-meter Ferris wheel at Rinku Pleasure Town Seacle offering panoramic views of Kansai Airport, the Izumi Mountains, and Osaka Bay. Opens at 10am.",
        kidNotes: "Children under elementary school age must ride with a paying guardian. A fun activity for the kids.",
        duration: "15–30 minutes",
        url: "https://www.seacle.jp/",
        tags: ["Ferris Wheel", "Views", "Kids"],
      },
      {
        id: "rinku-outlets",
        name: "Rinku Premium Outlet Mall",
        type: "attraction",
        category: "kids",
        lat: 34.4063,
        lng: 135.2959,
        description: "A large outlet mall near Rinku Town with international and Japanese brands. Good for last-minute shopping before the flight home. Don Quijote is also nearby for souvenirs and snacks.",
        kidNotes: "A relaxed afternoon activity. Don Quijote is great for picking up Japanese snacks and souvenirs.",
        duration: "1–2 hours",
        tags: ["Shopping", "Outlets", "Souvenirs"],
      },
      {
        id: "omo-dining-day9",
        name: "OMO Dining",
        type: "dining",
        category: "food",
        lat: 34.4338,
        lng: 135.2263,
        description: "Dinner at OMO Dining (6–9pm) in the hotel, or explore dining options in the Rinku area.",
        kidNotes: "A relaxed final dinner before the last night. The hotel restaurant is convenient.",
        mealType: "Dinner",
        tags: ["Dinner", "Hotel Restaurant"],
        isOption: true,
        optionGroup: "apr23-dinner",
      },
    ],
  },

  // ─── APR 24: DEPARTURE ─────────────────────────────────────────────────────
  {
    id: "apr24",
    date: "Apr 24",
    dayLabel: "Day 10",
    title: "Departure Day",
    subtitle: "Breakfast, airport shuttle, and fly home",
    region: "Rinku Town / Kansai Airport",
    mapCenter: { lat: 34.434, lng: 135.232 },
    mapZoom: 13,
    heroImage: TOPO_BG,
    tips: "Breakfast in hotel (6–10am). Airport shuttle booked at 8am. Arrive Singapore at 4:30pm. Order food or eat at the airport on arrival.",
    highlights: ["Breakfast at OMO Dining", "Airport shuttle at 8am", "Arrive Singapore 4:30pm"],
    locations: [
      {
        id: "omo-dining-breakfast",
        name: "OMO Dining (Breakfast)",
        type: "dining",
        category: "food",
        lat: 34.4338,
        lng: 135.2263,
        description: "Breakfast buffet at OMO Dining, open 6–10am. A relaxed final morning meal before heading to the airport.",
        kidNotes: "A buffet breakfast gives the kids plenty of options. Eat well before the flight.",
        mealType: "Breakfast",
        priceRange: "Included",
        tags: ["Breakfast", "Hotel Buffet"],
      },
      {
        id: "airport-shuttle",
        name: "Airport Shuttle (8am)",
        type: "transport",
        category: "transport",
        lat: 34.4338,
        lng: 135.2263,
        description: "Booked airport shuttle departs at 8am from the hotel to Kansai International Airport for the flight home.",
        kidNotes: "Pack the night before for a smooth morning. The shuttle is a quick and easy transfer to the airport.",
        tags: ["Transport", "Airport Shuttle", "Departure"],
      },
      {
        id: "kix-departure",
        name: "Kansai International Airport (Departure)",
        type: "transport",
        category: "transport",
        lat: 34.4338,
        lng: 135.2441,
        description: "Depart from Kansai International Airport. Arrive Singapore at 4:30pm. Order food or eat at the airport on arrival.",
        kidNotes: "Kansai Airport has a children's play area in the terminal — a great way to burn energy before boarding.",
        tags: ["Departure", "Airport", "Flight Home"],
      },
    ],
  },
];

export const categoryColors: Record<Category, string> = {
  nature: "#2D5016",
  culture: "#4A3728",
  food: "#C4622D",
  kids: "#1A6B8A",
  transport: "#5A5A7A",
  accommodation: "#7B4A8A",
  hike: "#5A7A2D",
};

export const categoryLabels: Record<Category, string> = {
  nature: "Nature",
  culture: "Culture",
  food: "Dining",
  kids: "Kids",
  transport: "Transport",
  accommodation: "Stay",
  hike: "Hike",
};

export const categoryEmoji: Record<Category, string> = {
  nature: "🌿",
  culture: "⛩️",
  food: "🍜",
  kids: "🎠",
  transport: "🚢",
  accommodation: "🏨",
  hike: "🥾",
};
